weblate/api/urls.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import include, path

from weblate.api.routers import WeblateRouter
from weblate.api.views import (
    AddonViewSet,
    CategoryViewSet,
    ChangeViewSet,
    ComponentListViewSet,
    ComponentViewSet,
    GroupViewSet,
    LanguageViewSet,
    MemoryViewSet,
    Metrics,
    ProjectViewSet,
    RoleViewSet,
    ScreenshotViewSet,
    Search,
    TasksViewSet,
    TranslationViewSet,
    UnitViewSet,
    UserViewSet,
)

# Routers provide an easy way of automatically determining the URL conf.
router = WeblateRouter()
router.register("users", UserViewSet)
router.register("groups", GroupViewSet)
router.register("roles", RoleViewSet)
router.register("projects", ProjectViewSet)
router.register("components", ComponentViewSet)
router.register("translations", TranslationViewSet)
router.register("memory", MemoryViewSet)
router.register("languages", LanguageViewSet)
router.register("component-lists", ComponentListViewSet)
router.register("changes", ChangeViewSet)
router.register("units", UnitViewSet)
router.register("screenshots", ScreenshotViewSet)
router.register("tasks", TasksViewSet, "task")
router.register("addons", AddonViewSet)
router.register("categories", CategoryViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path("metrics/", Metrics.as_view(), name="metrics"),
    path("search/", Search.as_view(), name="search"),
    path("", include(router.urls)),
]

weblate/legal/urls.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from weblate.legal.views import (
    ContractsView,
    CookiesView,
    LegalView,
    PrivacyView,
    TermsView,
    tos_confirm,
)

urlpatterns = [
    path("", LegalView.as_view(), name="index"),
    path("terms/", TermsView.as_view(), name="terms"),
    path("cookies/", CookiesView.as_view(), name="cookies"),
    path("privacy/", PrivacyView.as_view(), name="privacy"),
    path("contracts/", ContractsView.as_view(), name="contracts"),
    path("confirm/", tos_confirm, name="confirm"),
]

weblate/urls.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

import django.contrib.sitemaps.views
import django.views.i18n
import django.views.static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_control, cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView

import weblate.accounts.urls
import weblate.accounts.views
import weblate.addons.views
import weblate.api.urls
import weblate.auth.views
import weblate.checks.views
import weblate.fonts.views
import weblate.glossary.views
import weblate.lang.views
import weblate.machinery.views
import weblate.memory.views
import weblate.screenshots.views
import weblate.trans.views.about
import weblate.trans.views.acl
import weblate.trans.views.agreement
import weblate.trans.views.basic
import weblate.trans.views.charts
import weblate.trans.views.create
import weblate.trans.views.dashboard
import weblate.trans.views.edit
import weblate.trans.views.error
import weblate.trans.views.files
import weblate.trans.views.git
import weblate.trans.views.hooks
import weblate.trans.views.js
import weblate.trans.views.labels
import weblate.trans.views.lock
import weblate.trans.views.reports
import weblate.trans.views.search
import weblate.trans.views.settings
import weblate.trans.views.source
import weblate.trans.views.widgets
import weblate.wladmin.views
from weblate.auth.decorators import management_access
from weblate.configuration.views import CustomCSSView
from weblate.sitemaps import SITEMAPS
from weblate.trans.feeds import ChangesFeed, LanguageChangesFeed, TranslationChangesFeed
from weblate.trans.views.changes import ChangesCSVView, ChangesView, show_change
from weblate.utils.version import VERSION

handler400 = weblate.trans.views.error.bad_request
handler403 = weblate.trans.views.error.denied
handler404 = weblate.trans.views.error.not_found
handler500 = weblate.trans.views.error.server_error

widget_pattern = "<word:widget>-<word:color>.<extension:extension>"

URL_PREFIX = settings.URL_PREFIX
if URL_PREFIX:
    URL_PREFIX = URL_PREFIX.strip("/") + "/"

real_patterns = [
    path("", weblate.trans.views.dashboard.home, name="home"),
    path("projects/", weblate.trans.views.basic.list_projects, name="projects"),
    # Object display
    path(
        "projects/<object_path:path>/",
        weblate.trans.views.basic.show,
        name="show",
    ),
    # Engagement pages
    path(
        "engage/<object_path:path>/",
        weblate.trans.views.basic.show_engage,
        name="engage",
    ),
    # Component pages
    path(
        "guide/<object_path:path>/",
        weblate.trans.views.basic.guide,
        name="guide",
    ),
    path(
        "matrix/<object_path:path>/",
        weblate.trans.views.source.matrix,
        name="matrix",
    ),
    path(
        "js/matrix/<object_path:path>/",
        weblate.trans.views.source.matrix_load,
        name="matrix-load",
    ),
    path(
        "source/<int:pk>/context/",
        weblate.trans.views.source.edit_context,
        name="edit_context",
    ),
    # Translation pages
    path(
        "component-list/<name:name>/",
        weblate.trans.views.basic.show_component_list,
        name="component-list",
    ),
    path(
        "browse/<object_path:path>/",
        weblate.trans.views.edit.browse,
        name="browse",
    ),
    path(
        "translate/<object_path:path>/",
        weblate.trans.views.edit.translate,
        name="translate",
    ),
    path(
        "zen/<object_path:path>/",
        weblate.trans.views.edit.zen,
        name="zen",
    ),
    path(
        "download/<object_path:path>/",
        weblate.trans.views.files.download,
        name="download",
    ),
    path(
        "download-list/<name:name>/",
        weblate.trans.views.files.download_component_list,
        name="download_component_list",
    ),
    path(
        "upload/<object_path:path>/",
        weblate.trans.views.files.upload,
        name="upload",
    ),
    path(
        "unit/<int:unit_id>/delete/",
        weblate.trans.views.edit.delete_unit,
        name="delete-unit",
    ),
    path(
        "new-unit/<object_path:path>/",
        weblate.trans.views.edit.new_unit,
        name="new-unit",
    ),
    path(
        "auto-translate/<object_path:path>/",
        weblate.trans.views.edit.auto_translation,
        name="auto_translation",
    ),
    path(
        "replace/<object_path:path>/",
        weblate.trans.views.search.search_replace,
        name="replace",
    ),
    path(
        "bulk-edit/<object_path:path>/",
        weblate.trans.views.search.bulk_edit,
        name="bulk-edit",
    ),
    path("credits/", weblate.trans.views.reports.get_credits, name="credits"),
    path("counts/", weblate.trans.views.reports.get_counts, name="counts"),
    path(
        "credits/<object_path:path>/",
        weblate.trans.views.reports.get_credits,
        name="credits",
    ),
    path(
        "counts/<object_path:path>/",
        weblate.trans.views.reports.get_counts,
        name="counts",
    ),
    path(
        "new-lang/<object_path:path>/",
        weblate.trans.views.basic.new_language,
        name="new-language",
    ),
    path(
        "new-lang/",
        weblate.lang.views.CreateLanguageView.as_view(),
        name="create-language",
    ),
    path(
        "addons/<object_path:path>/",
        weblate.addons.views.AddonList.as_view(),
        name="addons",
    ),
    path(
        "addon/<int:pk>/",
        weblate.addons.views.AddonDetail.as_view(),
        name="addon-detail",
    ),
    path(
        "addon/<int:pk>/logs/",
        weblate.addons.views.AddonLogs.as_view(),
        name="addon-logs",
    ),
    path(
        "access/<name:project>/",
        weblate.trans.views.acl.manage_access,
        name="manage-access",
    ),
    path(
        "settings/<object_path:path>/",
        weblate.trans.views.settings.change,
        name="settings",
    ),
    path(
        "backups/<name:project>/",
        weblate.trans.views.settings.BackupsView.as_view(),
        name="backups",
    ),
    path(
        "backups/<name:project>/<name:backup>",
        weblate.trans.views.settings.BackupsDownloadView.as_view(),
        name="backups-download",
    ),
    path(
        "labels/<name:project>/",
        weblate.trans.views.labels.project_labels,
        name="labels",
    ),
    path(
        "labels/<name:project>/edit/<int:pk>/",
        weblate.trans.views.labels.label_edit,
        name="label_edit",
    ),
    path(
        "labels/<name:project>/delete/<int:pk>/",
        weblate.trans.views.labels.label_delete,
        name="label_delete",
    ),
    path(
        "fonts/<name:project>/",
        weblate.fonts.views.FontListView.as_view(),
        name="fonts",
    ),
    path(
        "fonts/<name:project>/font/<int:pk>/",
        weblate.fonts.views.FontDetailView.as_view(),
        name="font",
    ),
    path(
        "fonts/<name:project>/group/<int:pk>/",
        weblate.fonts.views.FontGroupDetailView.as_view(),
        name="font_group",
    ),
    path(
        "create/project/",
        weblate.trans.views.create.CreateProject.as_view(),
        name="create-project",
    ),
    path(
        "create/project/import/",
        weblate.trans.views.create.ImportProject.as_view(),
        name="create-project-import",
    ),
    path(
        "create/component/",
        weblate.trans.views.create.CreateComponentSelection.as_view(),
        name="create-component",
    ),
    path(
        "create/component/vcs/",
        weblate.trans.views.create.CreateComponent.as_view(),
        name="create-component-vcs",
    ),
    path(
        "create/component/zip/",
        weblate.trans.views.create.CreateFromZip.as_view(),
        name="create-component-zip",
    ),
    path(
        "create/component/doc/",
        weblate.trans.views.create.CreateFromDoc.as_view(),
        name="create-component-doc",
    ),
    path(
        "contributor-agreement/<object_path:path>",
        weblate.trans.views.agreement.agreement_confirm,
        name="contributor-agreement",
    ),
    path(
        "access/<name:project>/add/",
        weblate.trans.views.acl.add_user,
        name="add-user",
    ),
    path(
        "access/<name:project>/block/",
        weblate.trans.views.acl.block_user,
        name="block-user",
    ),
    path(
        "access/<name:project>/unblock/",
        weblate.trans.views.acl.unblock_user,
        name="unblock-user",
    ),
    path(
        "access/<name:project>/invite/",
        weblate.trans.views.acl.invite_user,
        name="invite-user",
    ),
    path(
        "access/<name:project>/remove/",
        weblate.trans.views.acl.delete_user,
        name="delete-user",
    ),
    path(
        "access/<name:project>/set/",
        weblate.trans.views.acl.set_groups,
        name="set-groups",
    ),
    path(
        "access/<name:project>/team/create/",
        weblate.trans.views.acl.create_group,
        name="create-project-group",
    ),
    path(
        "token/<name:project>/create/",
        weblate.trans.views.acl.create_token,
        name="create-project-token",
    ),
    # Used by weblate.org to render own activity chart on homepage
    path(
        "activity/month.json",
        weblate.trans.views.charts.monthly_activity_json,
        name="monthly_activity_json",
    ),
    # Comments
    path("comment/<int:pk>/", weblate.trans.views.edit.comment, name="comment"),
    path(
        "comment/<int:pk>/delete/",
        weblate.trans.views.edit.delete_comment,
        name="delete-comment",
    ),
    path(
        "comment/<int:pk>/resolve/",
        weblate.trans.views.edit.resolve_comment,

weblate/utils/urls.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import register_converter
from django.urls.converters import PathConverter, StringConverter

from weblate.trans.defines import CATEGORY_DEPTH

URL_DEPTH = CATEGORY_DEPTH + 3


class WeblateSlugConverter(StringConverter):
    regex = "[^/]+"


class GitPathConverter(StringConverter):
    regex = "(info/|git-upload-pack)[a-z0-9_/-]*"


class WordConverter(StringConverter):
    regex = "[^/-]+"


class WidgetExtensionConverter(StringConverter):
    regex = "(png|svg)"


class ObjectPathConverter(PathConverter):
    regex = f"[^/]+(/[^/]+){{0,{URL_DEPTH}}}"

    def to_python(self, value):
        return value.split("/")

    def to_url(self, value):
        return "/".join(value)


def register_weblate_converters() -> None:
    register_converter(WeblateSlugConverter, "name")
    register_converter(GitPathConverter, "git_path")
    register_converter(WordConverter, "word")
    register_converter(WidgetExtensionConverter, "extension")
    register_converter(ObjectPathConverter, "object_path")

weblate/api/models.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

weblate/configuration/models.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from django.db import models


class SettingQuerySet(models.QuerySet):
    def get_settings_dict(self, category: int) -> dict:
        return dict(self.filter(category=category).values_list("name", "value"))


class SettingCategory(models.IntegerChoices):
    UI = 1, "User Interface"
    MT = 2, "Machine Translation"


class Setting(models.Model):
    category = models.IntegerField(choices=SettingCategory.choices)
    name = models.CharField(max_length=100)
    value = models.JSONField()

    objects = SettingQuerySet.as_manager()

    class Meta:
        unique_together = [("category", "name")]
        verbose_name = "Setting"
        verbose_name_plural = "Settings"

    def __str__(self) -> str:
        return f"{self.get_category_display()}:{self.name}:{self.value}"

weblate/legal/models.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING, cast

from appconf import AppConf
from django.conf import settings
from django.db import models

from weblate.accounts.models import AuditLog
from weblate.utils.request import get_ip_address, get_user_agent

if TYPE_CHECKING:
    from weblate.auth.models import AuthenticatedHttpRequest

if "wllegal" in settings.INSTALLED_APPS:
    import wllegal.models

    DEFAULT_TOS_DATE = wllegal.models.LEGAL_TOS_DATE
else:
    DEFAULT_TOS_DATE = date(2017, 7, 2)


class WeblateLegalConf(AppConf):
    # Current TOS date
    LEGAL_TOS_DATE = DEFAULT_TOS_DATE

    class Meta:
        prefix = ""


class Agreement(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, unique=True, on_delete=models.deletion.CASCADE
    )
    tos = models.DateField(default=date(1970, 1, 1))
    address = models.GenericIPAddressField(null=True)
    user_agent = models.CharField(max_length=200, default="")
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "TOS agreement"
        verbose_name_plural = "TOS agreements"

    def __str__(self) -> str:
        return f"{self.user.username}:{self.tos}"

    @staticmethod
    def current_tos_date() -> date:
        return cast(
            "date",
            settings.LEGAL_TOS_DATE,  # type: ignore[misc]
        )

    def is_current(self):
        return self.tos == self.current_tos_date()

    def make_current(self, request: AuthenticatedHttpRequest) -> None:
        if not self.is_current():
            AuditLog.objects.create(
                self.user, request, "tos", date=self.current_tos_date().isoformat()
            )
            self.tos = self.current_tos_date()
            self.address = get_ip_address(request)
            self.user_agent = get_user_agent(request)
            self.save()

weblate/models.py
# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

weblate/templates/screenshots/screenshot_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load permissions %}
{% load compress %}
{% load crispy_forms_tags %}
{% load translations %}
{% load icons %}
{% load static %}

{% block extra_script %}
  {% compress js %}
    <script defer
            data-cfasync="false"
            src="{% static 'js/screenshots/clipboard-paste.js' %}{{ cache_param }}"></script>
  {% endcompress %}
{% endblock %}


{% block extra_styles %}
  <link rel="stylesheet"
        href="{% static 'styles/screenshots/screenshot_detail.css' %}{{ cache_param }}" />
{% endblock %}


{% block breadcrumbs %}
  {% path_object_breadcrumbs object.translation.component %}
  <li>
    <a href="{% url 'screenshots' path=object.translation.component.get_url_path %}">{% trans "Screenshots" %}</a>
  </li>
  <li>
    <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
  </li>
{% endblock %}


{% block content %}

  {% perm 'screenshot.delete' object.translation.component as user_can_delete_screenshot %}
  {% perm 'screenshot.edit' object.translation.component as user_can_edit_screenshot %}


  <div class="panel panel-default"
       id="sources-listing"
       data-href="{% url 'screenshot-js-get' pk=object.pk %}">
    <div class="panel-heading">
      <h4 class="panel-title">{% trans "Assigned source strings" %}</h4>
    </div>
    <div id="strings-table-container">{% include "screenshots/screenshot_sources_body.html" %}</div>
    <div class="panel-footer">{% trans "Screenshot is shown to add visual context for all listed source strings." %}</div>
  </div>

  {% if user_can_edit_screenshot %}
    <form id="screenshot-add-form" action="{% url 'screenshot-js-add' pk=object.pk %}">
      {% csrf_token %}
      <input type="hidden" name="source" id="add-source" />
    </form>
    <div class="panel panel-default" id="search-results">
      <div class="panel-heading">
        <h4 class="panel-title">{% trans "Assign source strings" %}</h4>
      </div>
      <div class="search-results">{% include "screenshots/screenshot_sources_search.html" %}</div>
      <div class="panel-footer">
        <div class="pull-right flip">
          <form class="form-inline">
            {% csrf_token %}
            <button data-href="{% url 'screenshot-js-ocr' pk=object.pk %}"
                    class="btn btn-warning"
                    id="screenshots-auto">{% trans "Automatically recognize" %}</button>
          </form>
        </div>
        <form class="form-inline double-submission">
          {% csrf_token %}
          <input class="textinput form-control"
                 type="text"
                 required="yes"
                 name="q"
                 id="search-input"
                 placeholder="{% trans "Source string search" %}" />
          <button data-href="{% url 'screenshot-js-search' pk=object.pk %}"
                  class="btn btn-primary"
                  id="screenshots-search">{% trans "Search" %}</button>
        </form>
      </div>
    </div>
  {% endif %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">{% trans "Image" %}</h4>
    </div>
    <div class="panel-body">{% include "screenshots/screenshot_show.html" with screenshot=object %}</div>
  </div>

  {% if user_can_edit_screenshot %}
    <form action="{{ object.get_absolute_url }}"
          method="post"
          enctype="multipart/form-data"
          id="screenshot-form-container">
      {% csrf_token %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">{% trans "Edit screenshot" %}</h4>
        </div>
        <div class="panel-body">{{ edit_form|crispy }}</div>
        <div class="panel-footer">
          <input type="submit" class="btn btn-primary" value="{% trans "Save" %}" />
        </div>
      </div>
    </form>

  {% endif %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">{% trans "Screenshot details" %}</h4>
    </div>

    <table class="table table-condensed table-striped">
      <tr>
        <th>{% trans "Created" %}</th>
        <td>{{ object.timestamp|naturaltime }}</td>
      </tr>
      <tr>
        <th>{% trans "Uploaded by" %}</th>
        <td>{{ object.get_user_display }}</td>
      </tr>
      <tr>
        <th>{% trans "Language" %}</th>
        <td>{{ object.translation.language }}</td>
      </tr>
    </table>

  </div>

  {% if user_can_delete_screenshot %}
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h4 class="panel-title">{% trans "Delete screenshot" %}</h4>
      </div>
      <div class="panel-body">

        <p class="help-block">{% trans "Deleting screenshot will remove it from all associated source strings." %}</p>

        <form action="{% url 'screenshot-delete' pk=object.pk %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        </form>

      </div>
    </div>
  {% endif %}

{% endblock %}

weblate/templates/screenshots/screenshot_list.html
{% extends "base.html" %}

{% load i18n %}
{% load permissions %}
{% load compress %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load icons %}
{% load static %}
{% load translations %}

{% block extra_script %}
  {% compress js %}
    <script defer
            data-cfasync="false"
            src="{% static 'js/screenshots/clipboard-paste.js' %}{{ cache_param }}"></script>
  {% endcompress %}
{% endblock %}


{% block breadcrumbs %}
  {% path_object_breadcrumbs object %}
  <li>
    <a href="{% url 'screenshots' path=object.get_url_path %}">{% trans "Screenshots" %}</a>
  </li>
{% endblock %}


{% block content %}

  {% perm 'screenshot.delete' object as user_can_delete_screenshot %}
  {% perm 'screenshot.edit' object as user_can_edit_screenshot %}

  {% if add_form %}
    <form action="{% url 'screenshots' path=object.get_url_path %}"
          method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">{% trans "Add new screenshot" %}</h4>
        </div>
        <div class="panel-body">
          <div id="screenshot-form-container">{{ add_form|crispy }}</div>
        </div>
        <div class="panel-footer">
          <input type="submit" class="btn btn-primary" value="{% trans "Upload" %}" />
        </div>
      </div>
    </form>
  {% endif %}

  <table class="sort table">
    <thead>
      <tr>
        <th>{% trans "Screenshot name" %}</th>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Strings" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for screenshot in object_list %}
        <tr>
          <th>
            <a href="{{ screenshot.get_absolute_url }}">{{ screenshot.name }}</a> <span class="badge">{{ screenshot.translation.language }}</span>
          </th>
          <td>
            <div class="shot-list">{% include "screenshots/screenshot_show.html" %}</div>
          </td>
          {% with count=screenshot.units.count %}
            <td data-value="{{ count }}">
              <a href="{{ screenshot.translation.get_translate_url }}?q={{ screenshot.filter_name }}">{{ count | intcomma }}</a>
              {% if count == 0 %}
                <span title="{% trans "There are no assigned strings." %}" class="red">{% icon "alert.svg" %}</span>
              {% endif %}
            </td>
          {% endwith %}
          <td>
            {% if user_can_edit_screenshot %}
              <a href="{{ screenshot.get_absolute_url }}" class="btn btn-primary">{% trans "Edit" %}</a>
            {% endif %}
          </td>
          <td>
            {% if user_can_delete_screenshot %}
              <form action="{% url 'screenshot-delete' pk=screenshot.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
              </form>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include "paginator.html" %}

{% endblock %}

weblate/templates/screenshots/screenshot_show.html
<a href="{{ screenshot.image.url }}"
   class="thumbnail"
   title="{{ screenshot.name }}"
   data-details-url="{% url 'screenshot' pk=screenshot.pk %}"
   {% if user_can_edit_screenshot %}data-can-edit{% endif %}>
  <img class="img-responsive"
       src="{{ screenshot.image.url }}"
       alt="{{ screenshot.name }}" />
</a>

weblate/templates/screenshots/screenshot_sources_body.html
{% load i18n %}
{% load permissions %}
{% load translations %}

{% perm 'screenshot.edit' object.translation.component as user_can_edit_screenshot %}

{% include "snippets/embed-units.html" with translation=object.translation component=object.translation.component units=object.units.all.order.prefetch.prefetch_full.count_screenshots show_location=True show_screenshots=True actions_template="screenshots/screenshot_sources_body_actions.html" %}

weblate/templates/screenshots/screenshot_sources_body_actions.html
{% load i18n %}

<a href="{{ unit.get_absolute_url }}" class="btn btn-primary">{% trans "View" %}</a>
{% if user_can_edit_screenshot %}
  <form class="inlineform"
        action="{% url 'screenshot-remove-source' pk=object.pk %}"
        method="post">
    {% csrf_token %}
    <input type="hidden" name="source" value="{{ unit.pk }}" />
    <button type="submit" class="btn btn-danger">{% trans "Remove" %}</button>
  </form>
{% endif %}

weblate/templates/screenshots/screenshot_sources_search.html
{% load i18n %}
{% load permissions %}
{% load translations %}

{% perm 'screenshot.edit' object.translation.component as user_can_edit_screenshot %}

{% include "snippets/embed-units.html" with translation=object.translation component=object.translation.component show_location=True show_screenshots=True loading_id="loading-screenshots" actions_template="screenshots/screenshot_sources_search_actions.html" search_query="" %}

weblate/templates/screenshots/screenshot_sources_search_actions.html
{% load i18n %}

<a class="add-string btn btn-primary" data-pk="{{ unit.pk }}">{% trans "Add to screenshot" %}</a>